import React from 'react';

function Teory(props){
    return (
        <div>
            <article>
                <h1>Teoria</h1>
            </article>
            <nav>
            <a className='teoryNav' href="#bdd">BDD</a>
            <a className='teoryNav' href="#robdd">ROBDD</a>
            <a className='teoryNav' href="#KodGraya">Kod Graya</a>
            <a className='teoryNav' href="#shannon">Rozkład Shanonna</a>
            
          </nav>  
          
         
          <div id="bdd">
            <div className='headsd'></div>
            <div className="articleHeader">BDD</div>
            <div className="articleBody">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae maximus justo, in vulputate felis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum ut iaculis erat. Donec ultrices quis tortor sed feugiat. Nunc vel lectus placerat, varius turpis eu, placerat neque. Aenean id augue urna. Morbi varius tempus pretium. Proin turpis mi, dignissim ut nisi a, hendrerit ultrices libero. Donec magna mauris, volutpat et ex id, viverra aliquam enim. Maecenas ultricies orci eget dui fermentum sagittis.

Fusce in laoreet metus. Etiam vel molestie risus. Fusce euismod, est at cursus dictum, sapien ex fringilla orci, eu ultrices lectus nibh vel orci. Donec lobortis libero vel justo ultrices placerat. Donec cursus, arcu vel dapibus fringilla, nisi ante vulputate lacus, quis blandit metus elit mollis lorem. Integer vitae laoreet tellus. Donec consequat odio augue, id aliquet nisi maximus at. Phasellus leo elit, convallis quis suscipit in, malesuada ut neque.

Vivamus sed molestie tellus. Nunc pretium molestie metus, eget ullamcorper diam mollis lacinia. Integer ut risus in nisl rhoncus porta eget vel nisl. Integer magna justo, fermentum in dui eu, sagittis rutrum elit. Praesent id purus ut justo pretium tempus vel sit amet libero. Vivamus placerat enim diam, non cursus justo mollis nec. Cras neque est, aliquet nec nisi aliquet, molestie malesuada eros. Nunc vestibulum erat ipsum. Curabitur bibendum lectus eu ipsum imperdiet, a molestie augue tempor. Vestibulum dignissim consectetur congue.

In mi mauris, ultrices eu maximus condimentum, sagittis eget augue. Nunc feugiat orci sed ipsum elementum, et accumsan diam tempor. Mauris rhoncus, magna vel dignissim tempor, sem tortor fringilla sem, at tincidunt augue libero quis diam. Etiam viverra ex in leo eleifend, ut dignissim diam vulputate. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed consectetur scelerisque urna iaculis finibus. Donec faucibus a mi sed ultrices. Proin fringilla aliquet feugiat. Etiam dignissim, risus ac convallis porttitor, augue sapien suscipit enim, ut hendrerit ante lectus in neque. Vestibulum erat quam, vehicula in maximus eget, ultricies sit amet sapien.

Suspendisse nec commodo mi. Phasellus venenatis orci ac elementum fringilla. Donec molestie venenatis lorem, nec eleifend leo mollis tempus. Maecenas elementum arcu dui, et dictum diam vestibulum ut. Mauris porttitor semper nisi, sit amet eleifend turpis gravida nec. Curabitur ut eleifend eros. Maecenas pulvinar aliquam egestas.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae maximus justo, in vulputate felis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum ut iaculis erat. Donec ultrices quis tortor sed feugiat. Nunc vel lectus placerat, varius turpis eu, placerat neque. Aenean id augue urna. Morbi varius tempus pretium. Proin turpis mi, dignissim ut nisi a, hendrerit ultrices libero. Donec magna mauris, volutpat et ex id, viverra aliquam enim. Maecenas ultricies orci eget dui fermentum sagittis.

Fusce in laoreet metus. Etiam vel molestie risus. Fusce euismod, est at cursus dictum, sapien ex fringilla orci, eu ultrices lectus nibh vel orci. Donec lobortis libero vel justo ultrices placerat. Donec cursus, arcu vel dapibus fringilla, nisi ante vulputate lacus, quis blandit metus elit mollis lorem. Integer vitae laoreet tellus. Donec consequat odio augue, id aliquet nisi maximus at. Phasellus leo elit, convallis quis suscipit in, malesuada ut neque.

Vivamus sed molestie tellus. Nunc pretium molestie metus, eget ullamcorper diam mollis lacinia. Integer ut risus in nisl rhoncus porta eget vel nisl. Integer magna justo, fermentum in dui eu, sagittis rutrum elit. Praesent id purus ut justo pretium tempus vel sit amet libero. Vivamus placerat enim diam, non cursus justo mollis nec. Cras neque est, aliquet nec nisi aliquet, molestie malesuada eros. Nunc vestibulum erat ipsum. Curabitur bibendum lectus eu ipsum imperdiet, a molestie augue tempor. Vestibulum dignissim consectetur congue.

In mi mauris, ultrices eu maximus condimentum, sagittis eget augue. Nunc feugiat orci sed ipsum elementum, et accumsan diam tempor. Mauris rhoncus, magna vel dignissim tempor, sem tortor fringilla sem, at tincidunt augue libero quis diam. Etiam viverra ex in leo eleifend, ut dignissim diam vulputate. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed consectetur scelerisque urna iaculis finibus. Donec faucibus a mi sed ultrices. Proin fringilla aliquet feugiat. Etiam dignissim, risus ac convallis porttitor, augue sapien suscipit enim, ut hendrerit ante lectus in neque. Vestibulum erat quam, vehicula in maximus eget, ultricies sit amet sapien.

Suspendisse nec commodo mi. Phasellus venenatis orci ac elementum fringilla. Donec molestie venenatis lorem, nec eleifend leo mollis tempus. Maecenas elementum arcu dui, et dictum diam vestibulum ut. Mauris porttitor semper nisi, sit amet eleifend turpis gravida nec. Curabitur ut eleifend eros. Maecenas pulvinar aliquam egestas.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae maximus justo, in vulputate felis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum ut iaculis erat. Donec ultrices quis tortor sed feugiat. Nunc vel lectus placerat, varius turpis eu, placerat neque. Aenean id augue urna. Morbi varius tempus pretium. Proin turpis mi, dignissim ut nisi a, hendrerit ultrices libero. Donec magna mauris, volutpat et ex id, viverra aliquam enim. Maecenas ultricies orci eget dui fermentum sagittis.

Fusce in laoreet metus. Etiam vel molestie risus. Fusce euismod, est at cursus dictum, sapien ex fringilla orci, eu ultrices lectus nibh vel orci. Donec lobortis libero vel justo ultrices placerat. Donec cursus, arcu vel dapibus fringilla, nisi ante vulputate lacus, quis blandit metus elit mollis lorem. Integer vitae laoreet tellus. Donec consequat odio augue, id aliquet nisi maximus at. Phasellus leo elit, convallis quis suscipit in, malesuada ut neque.

Vivamus sed molestie tellus. Nunc pretium molestie metus, eget ullamcorper diam mollis lacinia. Integer ut risus in nisl rhoncus porta eget vel nisl. Integer magna justo, fermentum in dui eu, sagittis rutrum elit. Praesent id purus ut justo pretium tempus vel sit amet libero. Vivamus placerat enim diam, non cursus justo mollis nec. Cras neque est, aliquet nec nisi aliquet, molestie malesuada eros. Nunc vestibulum erat ipsum. Curabitur bibendum lectus eu ipsum imperdiet, a molestie augue tempor. Vestibulum dignissim consectetur congue.

In mi mauris, ultrices eu maximus condimentum, sagittis eget augue. Nunc feugiat orci sed ipsum elementum, et accumsan diam tempor. Mauris rhoncus, magna vel dignissim tempor, sem tortor fringilla sem, at tincidunt augue libero quis diam. Etiam viverra ex in leo eleifend, ut dignissim diam vulputate. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed consectetur scelerisque urna iaculis finibus. Donec faucibus a mi sed ultrices. Proin fringilla aliquet feugiat. Etiam dignissim, risus ac convallis porttitor, augue sapien suscipit enim, ut hendrerit ante lectus in neque. Vestibulum erat quam, vehicula in maximus eget, ultricies sit amet sapien.

Suspendisse nec commodo mi. Phasellus venenatis orci ac elementum fringilla. Donec molestie venenatis lorem, nec eleifend leo mollis tempus. Maecenas elementum arcu dui, et dictum diam vestibulum ut. Mauris porttitor semper nisi, sit amet eleifend turpis gravida nec. Curabitur ut eleifend eros. Maecenas pulvinar aliquam egestas.</div>
          </div>
          <div id="robdd">
            <div className='headsd'></div>
            <div className="articleHeader">ROBDD</div>
            <div className="articleBody">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae maximus justo, in vulputate felis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum ut iaculis erat. Donec ultrices quis tortor sed feugiat. Nunc vel lectus placerat, varius turpis eu, placerat neque. Aenean id augue urna. Morbi varius tempus pretium. Proin turpis mi, dignissim ut nisi a, hendrerit ultrices libero. Donec magna mauris, volutpat et ex id, viverra aliquam enim. Maecenas ultricies orci eget dui fermentum sagittis.

Fusce in laoreet metus. Etiam vel molestie risus. Fusce euismod, est at cursus dictum, sapien ex fringilla orci, eu ultrices lectus nibh vel orci. Donec lobortis libero vel justo ultrices placerat. Donec cursus, arcu vel dapibus fringilla, nisi ante vulputate lacus, quis blandit metus elit mollis lorem. Integer vitae laoreet tellus. Donec consequat odio augue, id aliquet nisi maximus at. Phasellus leo elit, convallis quis suscipit in, malesuada ut neque.

Vivamus sed molestie tellus. Nunc pretium molestie metus, eget ullamcorper diam mollis lacinia. Integer ut risus in nisl rhoncus porta eget vel nisl. Integer magna justo, fermentum in dui eu, sagittis rutrum elit. Praesent id purus ut justo pretium tempus vel sit amet libero. Vivamus placerat enim diam, non cursus justo mollis nec. Cras neque est, aliquet nec nisi aliquet, molestie malesuada eros. Nunc vestibulum erat ipsum. Curabitur bibendum lectus eu ipsum imperdiet, a molestie augue tempor. Vestibulum dignissim consectetur congue.

In mi mauris, ultrices eu maximus condimentum, sagittis eget augue. Nunc feugiat orci sed ipsum elementum, et accumsan diam tempor. Mauris rhoncus, magna vel dignissim tempor, sem tortor fringilla sem, at tincidunt augue libero quis diam. Etiam viverra ex in leo eleifend, ut dignissim diam vulputate. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed consectetur scelerisque urna iaculis finibus. Donec faucibus a mi sed ultrices. Proin fringilla aliquet feugiat. Etiam dignissim, risus ac convallis porttitor, augue sapien suscipit enim, ut hendrerit ante lectus in neque. Vestibulum erat quam, vehicula in maximus eget, ultricies sit amet sapien.

Suspendisse nec commodo mi. Phasellus venenatis orci ac elementum fringilla. Donec molestie venenatis lorem, nec eleifend leo mollis tempus. Maecenas elementum arcu dui, et dictum diam vestibulum ut. Mauris porttitor semper nisi, sit amet eleifend turpis gravida nec. Curabitur ut eleifend eros. Maecenas pulvinar aliquam egestas.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae maximus justo, in vulputate felis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum ut iaculis erat. Donec ultrices quis tortor sed feugiat. Nunc vel lectus placerat, varius turpis eu, placerat neque. Aenean id augue urna. Morbi varius tempus pretium. Proin turpis mi, dignissim ut nisi a, hendrerit ultrices libero. Donec magna mauris, volutpat et ex id, viverra aliquam enim. Maecenas ultricies orci eget dui fermentum sagittis.

Fusce in laoreet metus. Etiam vel molestie risus. Fusce euismod, est at cursus dictum, sapien ex fringilla orci, eu ultrices lectus nibh vel orci. Donec lobortis libero vel justo ultrices placerat. Donec cursus, arcu vel dapibus fringilla, nisi ante vulputate lacus, quis blandit metus elit mollis lorem. Integer vitae laoreet tellus. Donec consequat odio augue, id aliquet nisi maximus at. Phasellus leo elit, convallis quis suscipit in, malesuada ut neque.

Vivamus sed molestie tellus. Nunc pretium molestie metus, eget ullamcorper diam mollis lacinia. Integer ut risus in nisl rhoncus porta eget vel nisl. Integer magna justo, fermentum in dui eu, sagittis rutrum elit. Praesent id purus ut justo pretium tempus vel sit amet libero. Vivamus placerat enim diam, non cursus justo mollis nec. Cras neque est, aliquet nec nisi aliquet, molestie malesuada eros. Nunc vestibulum erat ipsum. Curabitur bibendum lectus eu ipsum imperdiet, a molestie augue tempor. Vestibulum dignissim consectetur congue.

In mi mauris, ultrices eu maximus condimentum, sagittis eget augue. Nunc feugiat orci sed ipsum elementum, et accumsan diam tempor. Mauris rhoncus, magna vel dignissim tempor, sem tortor fringilla sem, at tincidunt augue libero quis diam. Etiam viverra ex in leo eleifend, ut dignissim diam vulputate. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed consectetur scelerisque urna iaculis finibus. Donec faucibus a mi sed ultrices. Proin fringilla aliquet feugiat. Etiam dignissim, risus ac convallis porttitor, augue sapien suscipit enim, ut hendrerit ante lectus in neque. Vestibulum erat quam, vehicula in maximus eget, ultricies sit amet sapien.

Suspendisse nec commodo mi. Phasellus venenatis orci ac elementum fringilla. Donec molestie venenatis lorem, nec eleifend leo mollis tempus. Maecenas elementum arcu dui, et dictum diam vestibulum ut. Mauris porttitor semper nisi, sit amet eleifend turpis gravida nec. Curabitur ut eleifend eros. Maecenas pulvinar aliquam egestas.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae maximus justo, in vulputate felis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum ut iaculis erat. Donec ultrices quis tortor sed feugiat. Nunc vel lectus placerat, varius turpis eu, placerat neque. Aenean id augue urna. Morbi varius tempus pretium. Proin turpis mi, dignissim ut nisi a, hendrerit ultrices libero. Donec magna mauris, volutpat et ex id, viverra aliquam enim. Maecenas ultricies orci eget dui fermentum sagittis.

Fusce in laoreet metus. Etiam vel molestie risus. Fusce euismod, est at cursus dictum, sapien ex fringilla orci, eu ultrices lectus nibh vel orci. Donec lobortis libero vel justo ultrices placerat. Donec cursus, arcu vel dapibus fringilla, nisi ante vulputate lacus, quis blandit metus elit mollis lorem. Integer vitae laoreet tellus. Donec consequat odio augue, id aliquet nisi maximus at. Phasellus leo elit, convallis quis suscipit in, malesuada ut neque.

Vivamus sed molestie tellus. Nunc pretium molestie metus, eget ullamcorper diam mollis lacinia. Integer ut risus in nisl rhoncus porta eget vel nisl. Integer magna justo, fermentum in dui eu, sagittis rutrum elit. Praesent id purus ut justo pretium tempus vel sit amet libero. Vivamus placerat enim diam, non cursus justo mollis nec. Cras neque est, aliquet nec nisi aliquet, molestie malesuada eros. Nunc vestibulum erat ipsum. Curabitur bibendum lectus eu ipsum imperdiet, a molestie augue tempor. Vestibulum dignissim consectetur congue.

In mi mauris, ultrices eu maximus condimentum, sagittis eget augue. Nunc feugiat orci sed ipsum elementum, et accumsan diam tempor. Mauris rhoncus, magna vel dignissim tempor, sem tortor fringilla sem, at tincidunt augue libero quis diam. Etiam viverra ex in leo eleifend, ut dignissim diam vulputate. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed consectetur scelerisque urna iaculis finibus. Donec faucibus a mi sed ultrices. Proin fringilla aliquet feugiat. Etiam dignissim, risus ac convallis porttitor, augue sapien suscipit enim, ut hendrerit ante lectus in neque. Vestibulum erat quam, vehicula in maximus eget, ultricies sit amet sapien.

Suspendisse nec commodo mi. Phasellus venenatis orci ac elementum fringilla. Donec molestie venenatis lorem, nec eleifend leo mollis tempus. Maecenas elementum arcu dui, et dictum diam vestibulum ut. Mauris porttitor semper nisi, sit amet eleifend turpis gravida nec. Curabitur ut eleifend eros. Maecenas pulvinar aliquam egestas.</div>
          </div>
          <div id="KodGraya">
            <div className='headsd'></div>
            <div className="articleHeader">Kod Graya</div>
            <div className="articleBody">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae maximus justo, in vulputate felis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum ut iaculis erat. Donec ultrices quis tortor sed feugiat. Nunc vel lectus placerat, varius turpis eu, placerat neque. Aenean id augue urna. Morbi varius tempus pretium. Proin turpis mi, dignissim ut nisi a, hendrerit ultrices libero. Donec magna mauris, volutpat et ex id, viverra aliquam enim. Maecenas ultricies orci eget dui fermentum sagittis.

Fusce in laoreet metus. Etiam vel molestie risus. Fusce euismod, est at cursus dictum, sapien ex fringilla orci, eu ultrices lectus nibh vel orci. Donec lobortis libero vel justo ultrices placerat. Donec cursus, arcu vel dapibus fringilla, nisi ante vulputate lacus, quis blandit metus elit mollis lorem. Integer vitae laoreet tellus. Donec consequat odio augue, id aliquet nisi maximus at. Phasellus leo elit, convallis quis suscipit in, malesuada ut neque.

Vivamus sed molestie tellus. Nunc pretium molestie metus, eget ullamcorper diam mollis lacinia. Integer ut risus in nisl rhoncus porta eget vel nisl. Integer magna justo, fermentum in dui eu, sagittis rutrum elit. Praesent id purus ut justo pretium tempus vel sit amet libero. Vivamus placerat enim diam, non cursus justo mollis nec. Cras neque est, aliquet nec nisi aliquet, molestie malesuada eros. Nunc vestibulum erat ipsum. Curabitur bibendum lectus eu ipsum imperdiet, a molestie augue tempor. Vestibulum dignissim consectetur congue.

In mi mauris, ultrices eu maximus condimentum, sagittis eget augue. Nunc feugiat orci sed ipsum elementum, et accumsan diam tempor. Mauris rhoncus, magna vel dignissim tempor, sem tortor fringilla sem, at tincidunt augue libero quis diam. Etiam viverra ex in leo eleifend, ut dignissim diam vulputate. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed consectetur scelerisque urna iaculis finibus. Donec faucibus a mi sed ultrices. Proin fringilla aliquet feugiat. Etiam dignissim, risus ac convallis porttitor, augue sapien suscipit enim, ut hendrerit ante lectus in neque. Vestibulum erat quam, vehicula in maximus eget, ultricies sit amet sapien.

Suspendisse nec commodo mi. Phasellus venenatis orci ac elementum fringilla. Donec molestie venenatis lorem, nec eleifend leo mollis tempus. Maecenas elementum arcu dui, et dictum diam vestibulum ut. Mauris porttitor semper nisi, sit amet eleifend turpis gravida nec. Curabitur ut eleifend eros. Maecenas pulvinar aliquam egestas.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae maximus justo, in vulputate felis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum ut iaculis erat. Donec ultrices quis tortor sed feugiat. Nunc vel lectus placerat, varius turpis eu, placerat neque. Aenean id augue urna. Morbi varius tempus pretium. Proin turpis mi, dignissim ut nisi a, hendrerit ultrices libero. Donec magna mauris, volutpat et ex id, viverra aliquam enim. Maecenas ultricies orci eget dui fermentum sagittis.

Fusce in laoreet metus. Etiam vel molestie risus. Fusce euismod, est at cursus dictum, sapien ex fringilla orci, eu ultrices lectus nibh vel orci. Donec lobortis libero vel justo ultrices placerat. Donec cursus, arcu vel dapibus fringilla, nisi ante vulputate lacus, quis blandit metus elit mollis lorem. Integer vitae laoreet tellus. Donec consequat odio augue, id aliquet nisi maximus at. Phasellus leo elit, convallis quis suscipit in, malesuada ut neque.

Vivamus sed molestie tellus. Nunc pretium molestie metus, eget ullamcorper diam mollis lacinia. Integer ut risus in nisl rhoncus porta eget vel nisl. Integer magna justo, fermentum in dui eu, sagittis rutrum elit. Praesent id purus ut justo pretium tempus vel sit amet libero. Vivamus placerat enim diam, non cursus justo mollis nec. Cras neque est, aliquet nec nisi aliquet, molestie malesuada eros. Nunc vestibulum erat ipsum. Curabitur bibendum lectus eu ipsum imperdiet, a molestie augue tempor. Vestibulum dignissim consectetur congue.

In mi mauris, ultrices eu maximus condimentum, sagittis eget augue. Nunc feugiat orci sed ipsum elementum, et accumsan diam tempor. Mauris rhoncus, magna vel dignissim tempor, sem tortor fringilla sem, at tincidunt augue libero quis diam. Etiam viverra ex in leo eleifend, ut dignissim diam vulputate. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed consectetur scelerisque urna iaculis finibus. Donec faucibus a mi sed ultrices. Proin fringilla aliquet feugiat. Etiam dignissim, risus ac convallis porttitor, augue sapien suscipit enim, ut hendrerit ante lectus in neque. Vestibulum erat quam, vehicula in maximus eget, ultricies sit amet sapien.

Suspendisse nec commodo mi. Phasellus venenatis orci ac elementum fringilla. Donec molestie venenatis lorem, nec eleifend leo mollis tempus. Maecenas elementum arcu dui, et dictum diam vestibulum ut. Mauris porttitor semper nisi, sit amet eleifend turpis gravida nec. Curabitur ut eleifend eros. Maecenas pulvinar aliquam egestas.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae maximus justo, in vulputate felis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum ut iaculis erat. Donec ultrices quis tortor sed feugiat. Nunc vel lectus placerat, varius turpis eu, placerat neque. Aenean id augue urna. Morbi varius tempus pretium. Proin turpis mi, dignissim ut nisi a, hendrerit ultrices libero. Donec magna mauris, volutpat et ex id, viverra aliquam enim. Maecenas ultricies orci eget dui fermentum sagittis.

Fusce in laoreet metus. Etiam vel molestie risus. Fusce euismod, est at cursus dictum, sapien ex fringilla orci, eu ultrices lectus nibh vel orci. Donec lobortis libero vel justo ultrices placerat. Donec cursus, arcu vel dapibus fringilla, nisi ante vulputate lacus, quis blandit metus elit mollis lorem. Integer vitae laoreet tellus. Donec consequat odio augue, id aliquet nisi maximus at. Phasellus leo elit, convallis quis suscipit in, malesuada ut neque.

Vivamus sed molestie tellus. Nunc pretium molestie metus, eget ullamcorper diam mollis lacinia. Integer ut risus in nisl rhoncus porta eget vel nisl. Integer magna justo, fermentum in dui eu, sagittis rutrum elit. Praesent id purus ut justo pretium tempus vel sit amet libero. Vivamus placerat enim diam, non cursus justo mollis nec. Cras neque est, aliquet nec nisi aliquet, molestie malesuada eros. Nunc vestibulum erat ipsum. Curabitur bibendum lectus eu ipsum imperdiet, a molestie augue tempor. Vestibulum dignissim consectetur congue.

In mi mauris, ultrices eu maximus condimentum, sagittis eget augue. Nunc feugiat orci sed ipsum elementum, et accumsan diam tempor. Mauris rhoncus, magna vel dignissim tempor, sem tortor fringilla sem, at tincidunt augue libero quis diam. Etiam viverra ex in leo eleifend, ut dignissim diam vulputate. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed consectetur scelerisque urna iaculis finibus. Donec faucibus a mi sed ultrices. Proin fringilla aliquet feugiat. Etiam dignissim, risus ac convallis porttitor, augue sapien suscipit enim, ut hendrerit ante lectus in neque. Vestibulum erat quam, vehicula in maximus eget, ultricies sit amet sapien.

Suspendisse nec commodo mi. Phasellus venenatis orci ac elementum fringilla. Donec molestie venenatis lorem, nec eleifend leo mollis tempus. Maecenas elementum arcu dui, et dictum diam vestibulum ut. Mauris porttitor semper nisi, sit amet eleifend turpis gravida nec. Curabitur ut eleifend eros. Maecenas pulvinar aliquam egestas.</div>
          </div>
          
          <div id="shannon">
            <div className='headsd'></div>
            <div className="articleHeader">Rozkład Shanonna</div>
            <div className="articleBody">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae maximus justo, in vulputate felis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum ut iaculis erat. Donec ultrices quis tortor sed feugiat. Nunc vel lectus placerat, varius turpis eu, placerat neque. Aenean id augue urna. Morbi varius tempus pretium. Proin turpis mi, dignissim ut nisi a, hendrerit ultrices libero. Donec magna mauris, volutpat et ex id, viverra aliquam enim. Maecenas ultricies orci eget dui fermentum sagittis.

Fusce in laoreet metus. Etiam vel molestie risus. Fusce euismod, est at cursus dictum, sapien ex fringilla orci, eu ultrices lectus nibh vel orci. Donec lobortis libero vel justo ultrices placerat. Donec cursus, arcu vel dapibus fringilla, nisi ante vulputate lacus, quis blandit metus elit mollis lorem. Integer vitae laoreet tellus. Donec consequat odio augue, id aliquet nisi maximus at. Phasellus leo elit, convallis quis suscipit in, malesuada ut neque.

Vivamus sed molestie tellus. Nunc pretium molestie metus, eget ullamcorper diam mollis lacinia. Integer ut risus in nisl rhoncus porta eget vel nisl. Integer magna justo, fermentum in dui eu, sagittis rutrum elit. Praesent id purus ut justo pretium tempus vel sit amet libero. Vivamus placerat enim diam, non cursus justo mollis nec. Cras neque est, aliquet nec nisi aliquet, molestie malesuada eros. Nunc vestibulum erat ipsum. Curabitur bibendum lectus eu ipsum imperdiet, a molestie augue tempor. Vestibulum dignissim consectetur congue.

In mi mauris, ultrices eu maximus condimentum, sagittis eget augue. Nunc feugiat orci sed ipsum elementum, et accumsan diam tempor. Mauris rhoncus, magna vel dignissim tempor, sem tortor fringilla sem, at tincidunt augue libero quis diam. Etiam viverra ex in leo eleifend, ut dignissim diam vulputate. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed consectetur scelerisque urna iaculis finibus. Donec faucibus a mi sed ultrices. Proin fringilla aliquet feugiat. Etiam dignissim, risus ac convallis porttitor, augue sapien suscipit enim, ut hendrerit ante lectus in neque. Vestibulum erat quam, vehicula in maximus eget, ultricies sit amet sapien.

Suspendisse nec commodo mi. Phasellus venenatis orci ac elementum fringilla. Donec molestie venenatis lorem, nec eleifend leo mollis tempus. Maecenas elementum arcu dui, et dictum diam vestibulum ut. Mauris porttitor semper nisi, sit amet eleifend turpis gravida nec. Curabitur ut eleifend eros. Maecenas pulvinar aliquam egestas.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae maximus justo, in vulputate felis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum ut iaculis erat. Donec ultrices quis tortor sed feugiat. Nunc vel lectus placerat, varius turpis eu, placerat neque. Aenean id augue urna. Morbi varius tempus pretium. Proin turpis mi, dignissim ut nisi a, hendrerit ultrices libero. Donec magna mauris, volutpat et ex id, viverra aliquam enim. Maecenas ultricies orci eget dui fermentum sagittis.

Fusce in laoreet metus. Etiam vel molestie risus. Fusce euismod, est at cursus dictum, sapien ex fringilla orci, eu ultrices lectus nibh vel orci. Donec lobortis libero vel justo ultrices placerat. Donec cursus, arcu vel dapibus fringilla, nisi ante vulputate lacus, quis blandit metus elit mollis lorem. Integer vitae laoreet tellus. Donec consequat odio augue, id aliquet nisi maximus at. Phasellus leo elit, convallis quis suscipit in, malesuada ut neque.

Vivamus sed molestie tellus. Nunc pretium molestie metus, eget ullamcorper diam mollis lacinia. Integer ut risus in nisl rhoncus porta eget vel nisl. Integer magna justo, fermentum in dui eu, sagittis rutrum elit. Praesent id purus ut justo pretium tempus vel sit amet libero. Vivamus placerat enim diam, non cursus justo mollis nec. Cras neque est, aliquet nec nisi aliquet, molestie malesuada eros. Nunc vestibulum erat ipsum. Curabitur bibendum lectus eu ipsum imperdiet, a molestie augue tempor. Vestibulum dignissim consectetur congue.

In mi mauris, ultrices eu maximus condimentum, sagittis eget augue. Nunc feugiat orci sed ipsum elementum, et accumsan diam tempor. Mauris rhoncus, magna vel dignissim tempor, sem tortor fringilla sem, at tincidunt augue libero quis diam. Etiam viverra ex in leo eleifend, ut dignissim diam vulputate. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed consectetur scelerisque urna iaculis finibus. Donec faucibus a mi sed ultrices. Proin fringilla aliquet feugiat. Etiam dignissim, risus ac convallis porttitor, augue sapien suscipit enim, ut hendrerit ante lectus in neque. Vestibulum erat quam, vehicula in maximus eget, ultricies sit amet sapien.

Suspendisse nec commodo mi. Phasellus venenatis orci ac elementum fringilla. Donec molestie venenatis lorem, nec eleifend leo mollis tempus. Maecenas elementum arcu dui, et dictum diam vestibulum ut. Mauris porttitor semper nisi, sit amet eleifend turpis gravida nec. Curabitur ut eleifend eros. Maecenas pulvinar aliquam egestas.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae maximus justo, in vulputate felis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum ut iaculis erat. Donec ultrices quis tortor sed feugiat. Nunc vel lectus placerat, varius turpis eu, placerat neque. Aenean id augue urna. Morbi varius tempus pretium. Proin turpis mi, dignissim ut nisi a, hendrerit ultrices libero. Donec magna mauris, volutpat et ex id, viverra aliquam enim. Maecenas ultricies orci eget dui fermentum sagittis.

Fusce in laoreet metus. Etiam vel molestie risus. Fusce euismod, est at cursus dictum, sapien ex fringilla orci, eu ultrices lectus nibh vel orci. Donec lobortis libero vel justo ultrices placerat. Donec cursus, arcu vel dapibus fringilla, nisi ante vulputate lacus, quis blandit metus elit mollis lorem. Integer vitae laoreet tellus. Donec consequat odio augue, id aliquet nisi maximus at. Phasellus leo elit, convallis quis suscipit in, malesuada ut neque.

Vivamus sed molestie tellus. Nunc pretium molestie metus, eget ullamcorper diam mollis lacinia. Integer ut risus in nisl rhoncus porta eget vel nisl. Integer magna justo, fermentum in dui eu, sagittis rutrum elit. Praesent id purus ut justo pretium tempus vel sit amet libero. Vivamus placerat enim diam, non cursus justo mollis nec. Cras neque est, aliquet nec nisi aliquet, molestie malesuada eros. Nunc vestibulum erat ipsum. Curabitur bibendum lectus eu ipsum imperdiet, a molestie augue tempor. Vestibulum dignissim consectetur congue.

In mi mauris, ultrices eu maximus condimentum, sagittis eget augue. Nunc feugiat orci sed ipsum elementum, et accumsan diam tempor. Mauris rhoncus, magna vel dignissim tempor, sem tortor fringilla sem, at tincidunt augue libero quis diam. Etiam viverra ex in leo eleifend, ut dignissim diam vulputate. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed consectetur scelerisque urna iaculis finibus. Donec faucibus a mi sed ultrices. Proin fringilla aliquet feugiat. Etiam dignissim, risus ac convallis porttitor, augue sapien suscipit enim, ut hendrerit ante lectus in neque. Vestibulum erat quam, vehicula in maximus eget, ultricies sit amet sapien.

Suspendisse nec commodo mi. Phasellus venenatis orci ac elementum fringilla. Donec molestie venenatis lorem, nec eleifend leo mollis tempus. Maecenas elementum arcu dui, et dictum diam vestibulum ut. Mauris porttitor semper nisi, sit amet eleifend turpis gravida nec. Curabitur ut eleifend eros. Maecenas pulvinar aliquam egestas.</div>
          </div>
          
        </div>
    )
}

export default Teory;

